FROM mirror.gcr.io/library/golang:1.24.1 AS builder
WORKDIR /build

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 go build -o app -ldflags "-s -w -X main.version= -X main.buildTimestamp= -X main.dirty=0  -extldflags -static" "./cmd/cloudprober/."

FROM mirror.gcr.io/library/alpine:latest AS runner
COPY --from=builder /build/app /usr/local/bin/cloudprober
RUN chmod +x /usr/local/bin/cloudprober
ENTRYPOINT ["/usr/local/bin/cloudprober"]
