name: Go Container Image
on:
  push:
    branches:
      - custom-master

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: fetch git commit short sha
        id: git_sha_short
        run: echo "git_sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
      - uses: ko-build/setup-ko@v0.6
      - run: |
          ko build --bare --tags "custom-sha-${GIT_SHA_SHORT}" --push ./cmd/cloudprober
        env:
          KO_DOCKER_REPO: ghcr.io/${{ github.repository }}
          GIT_SHA_SHORT: ${{ steps.git_sha_short.outputs.git_sha_short }}
